name: 'Setup QuickLisp'
description: >-
  Setup QuickLisp on a GitHub Runner where Common Lisp
  is already installed.
branding:
  icon: box
  color: blue
inputs:
  implementation:
    type: string
    default: 'sbcl'
    description: |
      The Common Lisp implementation to setup QuickLisp for.
      This can be one of the following values:
        
        abcl ecl sbcl

      in the future we would like to support all of

        abcl clasp clisp ecl gcl sbcl
      
  additional-systems:
    type: string
    required: false
    description: |
      The list of additional systems to download with QuickLisp.
outputs:
  quicklisp-home:
    value: '${{ steps.setup-quicklisp.outputs.quicklisp-home }}'
    description: >-
      The installation directory for the QuickLisp distribution.
  quicklisp-local-projects:
    value: '${{ steps.setup-quicklisp.outputs.quicklisp-local-projects }}'
    description: >-
      The local project directory for the QuickLisp distribution.
runs:
  using: 'composite'
  steps:
    - name: 'Install QuickLisp'
      if: runner.os == 'Linux'
      shell: sh
      run: >-
        sudo apt install
        cl-quicklisp
    - name: 'Install QuickLisp'
      if: runner.os == 'macOS'
      shell: sh
      run: >-
        sudo port install
        cl-quicklisp
    - name: 'Install QuickLisp'
      if: runner.os == 'Windows'
      shell: sh
      run: |
        curl -L -o ${GITHUB_ACTION_PATH}/quicklisp.lisp  https://beta.quicklisp.org/quicklisp.lisp
    - name: 'Setup Quicklisp'
      id: setup-quicklisp
      shell: sh
      run: >-
        PACKAGE=${{ github.repository }}
        QUICKLISP_HOME=${GITHUB_WORKSPACE}/quicklisp
        QUICKLISP_ADDITIONAL_SYSTEMS='${{ inputs.additional-systems }}'
        ${GITHUB_ACTION_PATH}/with_lisp_implementation ${{ inputs.implementation }}
        ${GITHUB_ACTION_PATH}/setup-quicklisp.lisp
    - name: 'Show QuickLisp Initialisation File'
      if: inputs.implementation == 'sbcl'
      id: debug-quicklisp-1
      shell: sh
      run: >-
        cat ${HOME}/.sbclrc
    - name: 'Show QuickLisp Initialisation File'
      if: inputs.implementation == 'sbcl'
      id: debug-quicklisp-2
      shell: sh
      run: >-
        echo '(warn "Reading Initialisation file.")' >> ${HOME}/.sbclrc
    - name: 'Require ALEXANDRIA'
      if: inputs.implementation == 'sbcl'
      id: debug-quicklisp-3
      shell: sh
      run: |
        ${GITHUB_ACTION_PATH}/with_lisp_implementation ${{ inputs.implementation }} <<EOF
        (ql:quickload "alexandria")
        (require "alexandria")
        EOF
