name: 'Setup QuickLisp'
description: >-
  Setup QuickLisp on a GitHub Runner where Common Lisp
  is already installed.
branding:
  icon: box
  color: blue
inputs:
  implementation:
    type: string
    default: 'sbcl'
    description: |
      The Common Lisp implementation to setup QuickLisp for.
      This can be one of the following values:
        
        abcl ecl sbcl

      in the future we would like to support all of

        abcl clasp clisp ecl gcl sbcl
      
  additional-systems:
    type: string
    required: false
    description: |
      The list of additional systems to download with QuickLisp.
outputs:
  quicklisp-home:
    value: '${{ steps.setup-quicklisp.outputs.quicklisp-home }}'
    description: >-
      The installation directory for the QuickLisp distribution.
  quicklisp-local-projects:
    value: '${{ steps.setup-quicklisp.outputs.quicklisp-home }}/local-projects'
    description: >-
      The local project directory for the QuickLisp distribution.
runs:
  using: 'composite'
  steps:
    - name: 'Install QuickLisp'
      if: runner.os == 'Linux'
      shell: sh
      run: >-
        sudo apt install
        cl-quicklisp
    - name: 'Install QuickLisp'
      if: runner.os == 'macOS'
      shell: sh
      run: >-
        sudo port install
        cl-quicklisp
    - name: 'Setup Quicklisp'
      id: setup-quicklisp
      shell: sh
      run: >-
        PACKAGE=${{ github.repository }}
        QUICKLISP_HOME=${HOME}/quicklisp
        QUICKLISP_ADDITIONAL_SYSTEMS='${{ inputs.additional-systems }}'
        ${{ github.action_path }}/with_lisp_implementation ${{ inputs.implementation }}
        ${{ github.action_path }}/setup-quicklisp.lisp
