name: 'Continuous Integration'
on:
  - workflow_dispatch
  - push

jobs:
  install-quicklisp-on-tier-1-platforms:
    strategy:
      matrix:
        implementation: ['abcl', 'ecl', 'sbcl']
        os: ['ubuntu-latest', 'macos-11', 'macos-12', 'macos-13']
    runs-on: '${{ matrix.os }}'
    name: 'Install QuickLisp'
    steps:
      - uses: actions/checkout@v3
      - name: 'Install MacPorts'
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
      - uses: melusina-org/setup-common-lisp@v1
        with:
          implementation: '${{ matrix.implementation }}'
      - uses: ./
        id: 'quicklisp'
        with:
          implementation: '${{ matrix.implementation }}'
          additional-systems: >-
            alexandria
            org.melusina.confidence
      - name: 'Validate installed implementation'
        run: |
          test -d '${{ steps.quicklisp.outputs.quicklisp-home }}'
          test -d '${{ steps.quicklisp.outputs.quicklisp-local-projects }}'

  install-quicklisp-on-tier-2-platforms:
    needs: install-quicklisp-on-tier-1-platforms
    strategy:
      matrix:
        implementation: ['clisp', 'gcl']
        os: ['ubuntu-latest', 'macos-11', 'macos-12', 'macos-13']
    runs-on: '${{ matrix.os }}'
    name: 'Install QuickLisp'
    steps:
      - uses: actions/checkout@v3
      - name: 'Install MacPorts'
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
      - uses: melusina-org/setup-common-lisp@v1
        continue-on-error: true
        with:
          implementation: '${{ matrix.implementation }}'
      - uses: ./
        continue-on-error: true
        id: 'quicklisp'
        with:
          implementation: '${{ matrix.implementation }}'
          additional-systems: >-
            alexandria
            org.melusina.confidence
      - name: 'Validate installed implementation'
        continue-on-error: true
        run: |
          test -d '${{ steps.quicklisp.outputs.quicklisp-home }}'
          test -d '${{ steps.quicklisp.outputs.quicklisp-local-projects }}'
